import Layout from "src/components/layouts/Layout";
import "./globals.css";
import { yekan } from "@/utils/fonts";


export const metadata = {
  title: "Next Tourino",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
